name=UMOZ
version=1.0.0
author=Moaaz
maintainer=Moaaz <moaaz.yahia.shrif@gmail.com>
sentence=A lightweight multitasking framework with a background task scheduler and real-time CPU profiling.
paragraph=UMOZ transforms your Arduino environment into a micro-RTOS. It injects performance boosters automatically into setup and loop, providing independent macro-based timers, an advanced background task scheduler, high-speed direct port manipulation, and continuous CPU usage monitoring without overhead.
category=Timing
url=https://github.com/Moaaz-i/UMOZ
architectures=*
