name=MicroTaskX
version=2.5.1
author=Moaaz Yahia Shrif
maintainer=Moaaz <[EMAIL_ADDRESS]>
sentence=An ultra-lightweight multitasking engine with a priority scheduler, macro timers, and real-time CPU profiling.
paragraph=MicroTaskX transforms Arduino into a micro-RTOS by providing a high-efficiency background task scheduler, independent macro-based timers, fast analog smoothing, direct port toggling, and continuous CPU usage monitoring with near-zero overhead.
category=Timing
url=https://github.com/Moaaz-i/MicroTaskX
architectures=*
